# Generated by Django 5.1.4 on 2026-05-28 06:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2; drives default factor region (e.g. GB, US).', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('admin', 'Admin')], default='analyst', max_length=16)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this user reviews data for. Superusers can be tenant-less.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text='Canonical key, e.g. diesel, natural_gas, grid_electricity, flight_short_haul_economy, hotel_night, rail.', max_length=80)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('region', models.CharField(help_text="ISO country code, eGRID subregion, or 'GLOBAL'.", max_length=8)),
                ('year', models.IntegerField()),
                ('source', models.CharField(choices=[('defra', 'DEFRA / UK DESNZ'), ('epa', 'US EPA')], max_length=16)),
                ('unit', models.CharField(help_text='Activity unit the factor applies to, e.g. litre, kWh, passenger_km, room_night, kg.', max_length=24)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=8, max_digits=14)),
                ('citation_url', models.URLField(help_text='Direct URL to the source workbook / PDF this row was extracted from.')),
                ('citation_sheet', models.CharField(blank=True, help_text='Sheet name and/or row reference inside the workbook.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['activity_type', 'region', '-year'],
                'indexes': [models.Index(fields=['activity_type', 'region', 'year'], name='core_emissi_activit_319c22_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity_type', 'region', 'year', 'source'), name='emission_factor_unique_per_dimension')],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('sap', 'SAP (procurement / fuel)'), ('utility_csv', 'Utility portal CSV'), ('utility_pdf', 'Utility bill PDF'), ('travel', 'Corporate travel export')], max_length=24)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('file_sha256', models.CharField(blank=True, help_text="Content hash of the uploaded bytes. We don't keep the file (Vercel filesystem is ephemeral and the parsed rows + hash are what auditors need).", max_length=64)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('rows_ingested', models.PositiveIntegerField(default=0)),
                ('rows_errored', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('partial', 'Partial (some rows errored)'), ('failed', 'Failed')], default='parsed', max_length=16)),
                ('error_summary', models.TextField(blank=True, help_text='Human-readable summary of why rows failed (parser errors, missing required fields).')),
                ('parser_notes', models.JSONField(blank=True, default=dict, help_text='Locale detected, header language, etc.')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_uploaded', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_batches', to='core.tenant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Human label, e.g. 'FY2024 Q1' or 'CY2024'.", max_length=80)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked')], default='open', max_length=16)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_locked', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('sap', 'SAP (procurement / fuel)'), ('utility_csv', 'Utility portal CSV'), ('utility_pdf', 'Utility bill PDF'), ('travel', 'Corporate travel export')], max_length=24)),
                ('source_record_id', models.CharField(blank=True, help_text='Native identifier from the source: SAP EBELN+EBELP, MPAN+period, Concur Trip ID + segment index, etc. Used to dedupe re-ingestions.', max_length=200)),
                ('raw_payload', models.JSONField(default=dict, help_text="The original parsed row as a JSON dict. Preserves every field we received even if we don't use it for emissions math.")),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_type', models.CharField(help_text='Canonical key matching EmissionFactor.activity_type (e.g. diesel, grid_electricity, flight_short_haul_economy).', max_length=80)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('quantity_raw', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_raw', models.CharField(max_length=24)),
                ('quantity_normalized', models.DecimalField(decimal_places=6, help_text='Converted into the unit the matched EmissionFactor expects.', max_digits=18)),
                ('unit_normalized', models.CharField(max_length=24)),
                ('period_start', models.DateField(help_text="Activity period start. NOT ingestion date. Utility bills span weird periods that don't align with calendar months — we store what the source said happened.")),
                ('period_end', models.DateField()),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_currency', models.CharField(blank=True, max_length=3)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='quantity_normalized * emission_factor.kg_co2e_per_unit.', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for follow-up'), ('locked', 'Locked (audit)')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False, help_text='True if a user has edited any normalized field since ingestion. Original ingested values live in raw_payload.')),
                ('flags', models.JSONField(blank=True, default=list, help_text="List of flag codes the flagging engine emitted, e.g. ['unit_inferred', 'factor_assumed', 'period_overlap'].")),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_reviewed', to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(blank=True, help_text='Null when no factor matched (row will be flagged factor_missing).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='core.emissionfactor')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.ingestionbatch')),
                ('reporting_period', models.ForeignKey(blank=True, help_text="Set when the record's period_end falls inside a known reporting period for the tenant. Lock state flows from here.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='core.reportingperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_end', '-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('flag', 'Flag'), ('unflag', 'Clear flag'), ('lock', 'Lock'), ('unlock', 'Unlock')], max_length=16)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='core.activityrecord')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRecordRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_name', models.CharField(max_length=80)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, help_text="Why the analyst changed it (e.g. 'meter reading corrected after supplier rebill', 'unit was L not GAL').", max_length=300)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_edits', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.activityrecord')),
            ],
            options={
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['record', 'edited_at'], name='core_activi_record__23679a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'label'), name='reporting_period_unique_label'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'status'], name='core_activi_tenant__730eba_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'scope', 'period_start'], name='core_activi_tenant__62fc13_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'activity_type', 'period_start'], name='core_activi_tenant__d36251_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['batch'], name='core_activi_batch_i_1c6033_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('source_record_id__gt', '')), fields=('tenant', 'source_system', 'source_record_id'), name='activity_record_unique_source_id_per_tenant'),
        ),
    ]
